# change port
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# mariadb
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/soundspace?serverTimezone=Asia/Seoul
    username: ss
    password: 0915

# jpa setting
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true

# jwt
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHN

--- # redis
spring:
  redis:
    host: localhost
    port: 6379

spotify:
  clientId: f3f0bcf58f5849b0bf5228f10fbf64f3
  clientSecret: 3b93ad6b89764a938a37f1f8b0595ed3

--- # swagger
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

genius:
  client-id: OprkTW4uD_JUPL7P__xUM-BsOaqANl_NSSTn4PodKFvye0-zC5-ObT68g0ZuqqF3
  client-secret: Rm7t_SFh9XhKCQFLbf1FpwW5yBnal8fAzbn6GHuC5zTLVykMEFT-ArNLu0mKPR2dox94BHruW4z0uNgZkLAWYg