# change port
server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# mariadb
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # jpa setting
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true

# jwt
jwt:
  secret: ${JWT_SECRET}

--- # redis
spring:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

#--- # redis
#spring:
#  redis:
#    host: localhost
#    port: 6379

--- # swagger
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

genius:
  client-id: ${GENIUS_CLIENT_ID}
  client-secret: ${GENIUS_CLIENT_SECRET}
